name: Deploy to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: ''

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Application
        run: dotnet publish MangaJaNaiConverterGui/MangaJaNaiConverterGui.csproj -c Release -o publish -r win-x64
      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk --prerelease
          vpk download github --repoUrl https://github.com/the-database/MangaJaNaiConverterGui
          vpk pack -u MangaJaNaiConverterGui -v ${{ github.event.inputs.version }} -p publish  -i ./MangaJaNaiConverterGui/assets/logo.ico -e MangaJaNaiConverterGui.exe
          vpk upload github --repoUrl https://github.com/the-database/MangaJaNaiConverterGui --publish --releaseName "${{ github.event.inputs.version }}" --tag ${{ github.event.inputs.version }} --token ${{ secrets.GITHUB_TOKEN }} --pre
